// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOwLMGhsxZ_X92RSxRuuJBGPmvQD29YPM',
    appId: '1:400221981329:web:53287f738ad912944b4d30',
    messagingSenderId: '400221981329',
    projectId: 'csistudytracker',
    authDomain: 'csistudytracker.firebaseapp.com',
    databaseURL: 'https://csistudytracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csistudytracker.firebasestorage.app',
    measurementId: 'G-7GKV226NDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAztw72sK8Vpc0LZrWLjZ-0LshpjgoNRhA',
    appId: '1:400221981329:android:06184f6f32d9530d4b4d30',
    messagingSenderId: '400221981329',
    projectId: 'csistudytracker',
    databaseURL: 'https://csistudytracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csistudytracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlUSftkNq-0WBYvIgteYLf4aCShMrPsBs',
    appId: '1:400221981329:ios:fa7af15daf5a56354b4d30',
    messagingSenderId: '400221981329',
    projectId: 'csistudytracker',
    databaseURL: 'https://csistudytracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csistudytracker.firebasestorage.app',
    iosBundleId: 'com.example.vscodeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlUSftkNq-0WBYvIgteYLf4aCShMrPsBs',
    appId: '1:400221981329:ios:fa7af15daf5a56354b4d30',
    messagingSenderId: '400221981329',
    projectId: 'csistudytracker',
    databaseURL: 'https://csistudytracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csistudytracker.firebasestorage.app',
    iosBundleId: 'com.example.vscodeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOwLMGhsxZ_X92RSxRuuJBGPmvQD29YPM',
    appId: '1:400221981329:web:f1d81ffef62687b04b4d30',
    messagingSenderId: '400221981329',
    projectId: 'csistudytracker',
    authDomain: 'csistudytracker.firebaseapp.com',
    databaseURL: 'https://csistudytracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csistudytracker.firebasestorage.app',
    measurementId: 'G-THHL49M8E1',
  );
}
